from os import getenv
from dotenv import load_dotenv
load_dotenv()
STRING = getenv("STRING")
STRING2 = getenv("STRING2")
STRING3 = getenv("STRING3")
STRING4 = getenv("STRING4")
STRING5 = getenv("STRING5")
STRING6 = getenv("STRING6")
STRING7 = getenv("STRING7")
STRING8 = getenv("STRING8")
STRING9 = getenv("STRING9")
STRING10 = getenv("STRING10")
STRINGX1 = getenv("STRING11")
STRINGX2 = getenv("STRING12")
STRINGX3 = getenv("STRING13")
STRINGX4 = getenv("STRING14")
STRINGX5 = getenv("STRING15")
STRINGX6 = getenv("STRING16")
STRINGX7 = getenv("STRING17")
STRINGX8 = getenv("STRING18")
STRINGX9 = getenv("STRING19")
STRINGXX = getenv("STRING20")
STRINGXX1 = getenv("STRING21")
STRINGXX2 = getenv("STRING22")
STRINGXX3 = getenv("STRING23")
STRINGXX4 = getenv("STRING24")
STRINGXX5 = getenv("STRING25")
STRINGXX6 = getenv("STRING26")
STRINGXX7 = getenv("STRING27")
STRINGXX8 = getenv("STRING28")
STRINGXX9 = getenv("STRING29")
STRINGXXX = getenv("STRING30")
STRINGXXX1 = getenv("STRING31")
STRINGXXX2 = getenv("STRING32")
STRINGXXX3 = getenv("STRING33")
STRINGXXX4 = getenv("STRING34")
STRINGXXX5 = getenv("STRING35")
STRINGXXX6 = getenv("STRING36")
STRINGXXX7 = getenv("STRING37")
STRINGXXX8 = getenv("STRING38")
STRINGXXX9 = getenv("STRING39")
STRINGXXXX = getenv("STRING40")
API_ID = getenv("API_ID")
API_HASH = getenv("API_HASH")
BIO_MESSAGE = getenv("BIO")
SUDO_USERS = list(map(int, getenv("SUDO_USERS").split()))
OWNER_ID = list(map(int, getenv("OWNER_ID").split()))
SUDO_USERS.append(OWNER_ID)
OWNER_NAME = getenv("OWNER_NAME")
SUDO_USERS = list(SUDO_USERS)
HNDLR = getenv("HNDLR", default=".")
